# Build and deploy the site
name: Publish app and deploy cloud functions
on:
  workflow_dispatch:
  push:
    branches: [main]

defaults:
  run:
    shell: bash

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
    secrets: inherit
  build:
    needs: [test]
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: make install
      - name: Update and process data
        run: make data
      - name: Generate bundled files
        run: make build
  deploy_cloud_functions:
    needs: [test, build]
    runs-on: [ubuntu-latest]
    steps:
      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          # workload_identity_provider: "projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider"
          service_account: ${{ secrets.GCP_SVC_ACCT }}
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - id: "deploy"
        uses: "google-github-actions/deploy-cloud-functions@v1"
        with:
          name: "data"
          runtime: "nodejs16"

    deploy_github_pages:
      needs: [test, build]
      runs-on: [ubuntu-latest]
      steps:
        # Example of using the output
        - id: "test"
          run: 'curl "${{ steps.deploy.outputs.url }}"'
        - name: Upload artifact
          uses: actions/upload-pages-artifact@v1
          with:
            # Upload entire repository
            path: "public"
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v1
