# Build and deploy the site
name: Deploy cloud functions
on:
  workflow_dispatch:
  workflow_call:

defaults:
  run:
    shell: bash

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 16

      # Praise the lord this page was helpful: https://github.com/actions/cache/blob/main/caching-strategies.md
      - name: Restore cached node modules
        id: npm-cache
        uses: actions/cache@v3
        with:
          path: |
            ./node_modules
            ./functions/node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}

      - name: install node modules, if needed
        run: make install
        if: steps.npm-cache.outputs.cache-hit != true

      - run: make data

      - run: make build

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          # workload_identity_provider: "projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider"
          service_account: ${{ secrets.GCP_SVC_ACCT }}
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: "Deploy functions"
        uses: "google-github-actions/deploy-cloud-functions@v1"
        with:
          name: data
          runtime: nodejs16
          source_dir: functions
