# Build and deploy the site
name: Tests and checks
on:
  workflow_call:
  workflow_dispatch:
  pull_request:

defaults:
  run:
    shell: bash

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
# permissions:
#   contents: read
#   pages: write
#   id-token: write

# Allow one concurrent deployment
concurrency:
  group: "test"
  cancel-in-progress: true

jobs:
  install:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 16

      - name: Cache node modules
        id: npm-cache
        uses: actions/cache@v3
        with:
          path: |
            ./node_modules
            ./functions/node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}

      - name: Install if needed
        if: ${{ steps.npm-cache.outputs.cache-hit != 'true' }}
        continue-on-error: true
        run: make install

  data_validation:
    runs-on: [ubuntu-latest]
    needs: [install]
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version: 16

      - uses: actions/cache@v3
        name: Restore the node modules from cache
        id: npm-cache
        with:
          path: |
            ./node_modules
            ./functions/node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}

      - name: Update and process data
        run: make data

      - name: Tests
        run: make test

  test_build:
    runs-on: [ubuntu-latest]
    needs: [install]
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version: 16

      # Restore node_modules from previous job in this workflow run
      - uses: actions/cache@v3
        name: Restore the cached node modules
        id: npm-cache
        with:
          path: |
            ./node_modules
            ./functions/node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}

      - name: Generate data and related files
        run: make data

      - name: Generate bundled files
        run: make build
